### ISSUE TITLE
Error when upgrading appengine to version 1.9.54

### ISSUE THREAD

**Issue by kassemshehady** [GoogleCloudPlatform/cloud-pubsub-samples-java#46]
java.lang.IllegalAccessError: tried to access class com.google.appengine.repackaged.com.google.common.base.Platform from class com.google.appengine.repackaged.com.google.common.base.Ticker

https://github.com/GoogleCloudPlatform/cloud-pubsub-samples-java/blob/master/appengine-push/src/main/java/com/google/cloud/pubsub/client/demos/appengine/servlet/SendMessageServlet.java

@lesv

**Comment by lesv** [comment]
@jabubake PTAL

**Comment by chanseokoh** [comment]
Could this be https://issuetracker.google.com/issues/63123716?

**Comment by ludoch** [comment]
Yes, fixed in next gae sdk push...

**Comment by chanseokoh** [comment]
I believe this is fixed with the latest App Engine SDK.
